{
 "title": "Service Desk monitoring",
 "description": "Monitor KPIs of IT service desk",
 "time": { "from": "2022-12-22T19:42:58.617Z", "to": "2025-09-01T07:36:53.061Z" },
 "templating": {
  "list": [
   { "name": "table", "label": "table", "query": "tickets" },
   { "name": "schema", "label": "schema", "query": "regional_office" }
  ]
 },
 "panels": [
  { "title": "Ticket count", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total monthly tickets",
   "type": "timeseries",
   "description": "Total number of tickets over time",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 1 },
   "targets": [
    {
     "dataset": "tickets",
     "rawSql": "\tSELECT \n\t    month_start,\n\t    COUNT(*) AS total_tickets\n\tFROM (\n\t    SELECT \t      \n\t        DATE_TRUNC('month', time_created) AS month_start\n\t    FROM $schema.$table\n\t) AS t\n\tGROUP BY month_start\n\tORDER BY month_start;\n"
    }
   ]
  },
  {
   "title": "Ticket status overview",
   "type": "piechart",
   "description": "Number of ticket statuses upon closure",
   "gridPos": { "h": 11, "w": 7, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "dataset": "tickets",
     "rawSql": "SELECT status,\n\t    COUNT(*) AS total_tickets\n\t    FROM $schema.$table\n\tWHERE active = false\n\tGROUP BY status;\n\n"
    }
   ]
  },
  { "title": "Response & Resolution KPIs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "Time to first response",
   "type": "timeseries",
   "description": "Average time between ticket creation and agent assignment",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "m" } },
   "targets": [
    {
     "dataset": "service_desk",
     "rawSql": "SELECT\nmonth_start,\nAVG((EXTRACT (EPOCH from time_assigned) - EXTRACT (EPOCH from time_created))/60)::INT AS time_to_first_response\nFROM(\n  SELECT \n  time_assigned,\n  time_created,\n  DATE_TRUNC('month', time_created) AS month_start\n  FROM $schema.$table\n) AS t\nGROUP BY month_start\nORDER BY month_start"
    }
   ]
  },
  {
   "title": "Time to resolution ",
   "type": "barchart",
   "description": "average time from ticket creation to closure per month",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "h" } },
   "targets": [
    {
     "dataset": "tickets",
     "rawSql": "SELECT  month_start,\n   EXTRACT(EPOCH FROM AVG(time_closed - time_created)) / 3600 AS time_to_resolution\nFROM (\n    SELECT \n        DATE_TRUNC('month', time_created) AS month_start,\n        time_created,\n        time_closed\n    FROM $schema.$table\n) t\nGROUP BY month_start\nORDER BY month_start;\n"
    }
   ]
  },
  {
   "title": "Ticket closure rate",
   "type": "timeseries",
   "description": "Percentage of tickets closed in 48h per month",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "dataset": "tickets",
     "rawSql": "\tSELECT \n\t    month_start,\n\t    ROUND(\n\t        AVG(\n\t            CASE \n\t                WHEN (time_closed - time_created) <= INTERVAL '48 hours' \n\t                THEN 1 \n\t                ELSE 0 \n\t            END\n\t        ) * 100, 2\n\t    ) AS rate\n\tFROM (\n\t    SELECT \n\t        time_closed, \n\t        time_created,\n\t        DATE_TRUNC('month', time_created) AS month_start\n\t    FROM $schema.$table\n\t) t\n\tGROUP BY month_start\nORDER BY month_start;"
    }
   ]
  },
  { "title": "Callback incidents", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 } },
  {
   "title": "Callback incidents",
   "type": "barchart",
   "description": "Number of tickets requiring customer callback ",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 34 },
   "targets": [
    {
     "dataset": "service_desk",
     "rawSql": "SELECT \nCOUNT (ticket_id) AS no_of_tickets,\nmonth_start\n\tFROM (\n\t    SELECT \t  \n\t\tticket_id,\n\t        DATE_TRUNC('month', time_created) AS month_start\n\t    FROM $schema.$table\n\t\tWHERE needed_call = true\n\t) AS t\nGROUP BY month_start\nORDER BY month_start;"
    }
   ]
  },
  { "title": "Customer satisfaction", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 46 } },
  {
   "title": "Customer rating",
   "type": "timeseries",
   "description": "Average customer satisfaction per month expressed in a rating 1-5",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 47 },
   "targets": [
    {
     "dataset": "tickets",
     "rawSql": "\tSELECT ROUND(AVG(success_rate),2) AS customer_rating,\n\t\t    month_start\n\t\tFROM (\n\t\t    SELECT \t  \n\t\t\tsuccess_rate,\n\t\t        DATE_TRUNC('month', time_created) AS month_start\n\t\t    FROM $schema.$table\n\t\t) AS t\n\t\tGROUP BY month_start\n\t\tORDER BY month_start;\n"
    }
   ]
  }
 ]
}